# Generated by Django 4.0.6 on 2022-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=120, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('language', models.CharField(choices=[('hi', 'hello')], max_length=120, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
            ],
        ),
    ]
