# Generated by Django 4.0.6 on 2022-07-24 13:27

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=5, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=120)),
                ('body', models.TextField()),
                ('language', models.CharField(choices=[('bash', 'Bash'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('go', 'Go'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('md', 'MarkDown'), ('php', 'PHP'), ('plaintext', 'PlainText'), ('python', 'Python'), ('rb', 'Ruby')], default='plaintext', max_length=120)),
                ('theme', models.CharField(choices=[('default', 'Default Light'), ('dark', 'Default Dark'), ('atom-one-light', 'Atom One Light'), ('atom-one-dark', 'Atom One Dark'), ('github', 'Github Light'), ('github-dark', 'Github Dark')], default='default', max_length=120)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
            ],
        ),
    ]
