# Generated by Django 4.0.6 on 2022-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="expires_in",
            field=models.SmallIntegerField(
                choices=[(1, "One Day"), (7, "One Week"), (30, "One Month")],
                default=1,
                verbose_name="Expires in",
            ),
        ),
    ]
