# Generated by Django 4.0.6 on 2022-07-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='expires_at',
            field=models.CharField(choices=[('1d', 'One Day'), ('1w', 'One Week'), ('1m', 'One Month')], default='1d', max_length=2),
        ),
    ]
