# Generated by Django 4.0.6 on 2022-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_alter_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('bash', 'Bash'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('go', 'Go'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('md', 'markdown'), ('php', 'PHP'), ('plaintext', 'PlainText'), ('python', 'Python'), ('rb', 'Ruby')], default='plaintext', max_length=120, verbose_name='Language'),
        ),
    ]
