# Generated by Django 4.0.6 on 2022-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('default.min.css', 'default'), ('dark.min.css', 'default dark')], default='default', max_length=120),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('bash', 'Bash'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('go', 'Go'), ('html', 'HTML'), ('java', 'Java'), ('js', 'JavaScript'), ('json', 'JSON'), ('lua', 'Lua'), ('md', 'MarkDown'), ('php', 'PHP'), ('plaintext', 'PlainText'), ('python', 'Python'), ('rb', 'Ruby')], default='plaintext', max_length=120),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='Untitled', max_length=120),
        ),
    ]
