# Generated by Django 4.0.6 on 2022-07-20 10:41

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_snippet_theme_alter_snippet_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg12345', length=5, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('default.min.css', 'default'), ('dark.min.css', 'dark'), ('atom-one-light.min.css', 'atom-one-light'), ('atom-one-dark.min.css', 'atom-one-dark'), ('github.min.css', 'github-light'), ('github-dark.min.css', 'github-dark')], default='default', max_length=120),
        ),
    ]
