# Generated by Django 4.0.6 on 2022-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0009_alter_snippet_id_alter_snippet_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('default.min.css', 'default'), ('dark.min.css', 'dark'), ('atom-one-light.min.css', 'atom-one-light'), ('atom-one-dark.min.css', 'atom-one-dark'), ('github.min.css', 'github-light'), ('github-dark.min.css', 'github-dark')], default='default.min.css', max_length=120),
        ),
    ]
