# Generated by Django 4.0.6 on 2022-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0010_alter_snippet_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Light'), ('dark', 'Default Dark'), ('atom-one-light', 'Atom One Light'), ('atom-one-dark', 'Atom One Dark'), ('github', 'Github Light'), ('github-dark', 'Github Dark')], default='default', max_length=120),
        ),
    ]
