# Generated by Django 4.0.6 on 2022-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_day_downloads", models.PositiveIntegerField()),
                ("last_week_downloads", models.PositiveIntegerField()),
                ("last_month_downloads", models.PositiveIntegerField()),
                ("total_downloads", models.PositiveIntegerField()),
                ("total_service_stars", models.PositiveIntegerField()),
                ("total_package_stars", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
