# Generated by Django 4.0.6 on 2022-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='overall_downloads',
            new_name='last_month_downloads',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='overall_stars',
            new_name='last_week_downloads',
        ),
        migrations.AddField(
            model_name='statistic',
            name='today_total_downloads',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_stars',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
