# Generated by Django 4.0.6 on 2022-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypi', '0003_rename_today_total_downloads_statistic_last_day_downloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='total_stars',
            new_name='total_package_stars',
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_service_stars',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
