# Generated by Django 4.0.6 on 2022-09-07 07:33

from django.db import migrations, models

import modals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Modal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=400)),
                (
                    "footer_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "footer_description",
                    models.TextField(blank=True, max_length=400, null=True),
                ),
                (
                    "icon",
                    models.FileField(
                        upload_to="modal/icon/",
                        validators=[modals.models.Modal.validate_file_extension],
                    ),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
