# Generated by Django 4.0.6 on 2022-09-08 05:27

import django.utils.timezone
from django.db import migrations, models

import modals.models


class Migration(migrations.Migration):

    dependencies = [
        ("modals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modal",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="modal/icon/",
                validators=[modals.models.Modal.validate_file_extension],
            ),
        ),
    ]
