# Generated by Django 4.0.6 on 2022-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="absract",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
