# Generated by Django 4.0.6 on 2022-07-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_absract_alter_blog_published_at_alter_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='absract',
            new_name='abstract',
        ),
    ]
