# Generated by Django 4.0.6 on 2022-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tag_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
